import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import s from "@/app/page.module.css";
import Link from "next/link";
import Navbar from "../components/Navbar";
// import styles from "./layout.module.css";
import EasterRabbit from "../components/EasterRabbit";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TEST PRODUCT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className="animated-bg">
        <Navbar />

        {children}
        <EasterRabbit />
      </body>
    </html>
  );
}
